### ISSUE TITLE
Timed out waiting for a response from the computer

### ISSUE THREAD

**Issue by JADYFAST** [mediabots/Linux-to-Windows-with-QEMU#1]
I ve tried tried everything, i still cant use vnc viewer.. i kept getting "Timed out waiting for a response from the computer" i use scaleway.com Starter Plan : 1-S

**Comment by JADYFAST** [comment]
changed -vnc :0 to -vnc :9 and connected to 9 it worked!!

**Comment by mediabots** [comment]
oh! sorry I missed your last email.
Good to know that, you sorted it out :)

Are you sure , you are not running any other qemu-kvm instances in your vps/server?

I am asking because, a port normally get blocked only if another instance(qemu) already running on that port.

anyway you can kill all running qemu with the below command :-

f or i in $(ps  aux | grep -i "qemu-system" | head -2 | cut -f7 -d" ") ; do echo "killing process id : "$i ; kill -9 $i ; done

Regards

**Comment by vkosovskikh** [comment]
I have timeout in VNC Viewer and can't connect to VPS. Ubuntu 18.04, Scaleway. What to do?

**Comment by vkosovskikh** [comment]
Ubuntu 16.04 has no timeout problem, but gives the message: "Guest has not initialized the display (yet)". What does it mean?

**Comment by mediabots** [comment]
Sounds like your VPS is using RAID 
Which hosting were you using?

  
>Воскресенье, 22 марта 2020, 18:52 +03:00 от Vladislav Kosovskikh <notifications@github.com>:
> 
> 
>Ubuntu 16.04 has no timeout problem, but gives the message: "Guest has not initialized the display (yet)". What does it mean?
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Media Bots

**Comment by vkosovskikh** [comment]
> Sounds like your VPS is using RAID  Which hosting were you using?  
> Воскресенье, 22 марта 2020, 18:52 +03:00 от Vladislav Kosovskikh ***@***.***>:     Ubuntu 16.04 has no timeout problem, but gives the message: "Guest has not initialized the display (yet)". What does it mean? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub , or unsubscribe .
>     -- Media Bots

Scaleway

**Comment by mediabots** [comment]
Scaleway recently updated their hardware. They made changes in their Plans, They are going to make chnages in their pricee too from August.
So I don’t think this technique would on them for anymore.
You can try with other VPS, like DigitalOcean 
Or you can buy a cheap server from  https://oneprovider.com/dedicated-servers/1gbps

  
>Четверг, 23 июля 2020, 8:14 +03:00 от Vladislav Kosovskikh <notifications@github.com>:
> 
> 
>Sounds like your VPS is using RAID  Which hosting were you using?  
>Воскресенье, 22 марта 2020, 18:52 +03:00 от Vladislav Kosovskikh  @ .***>:     Ubuntu 16.04 has no timeout problem, but gives the message: "Guest has not initialized the display (yet)". What does it mean? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub , or unsubscribe .
>    -- Media Bots
Scaleway
—
You are receiving this because you modified the open/close state.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
--
Media Bots
