### ISSUE TITLE
Error on line 29

### ISSUE THREAD

**Issue by thewebcapsule** [mediabots/Linux-to-Windows-with-QEMU#6]
It shows a syntax error at elif. Line 29. In both Ubuntu and CentOS distros.

**Comment by mediabots** [comment]
Script is running smoothly!
Just tested on Ubuntu Bionic



Something must be wrong from your end!
either it happened during to copy-paste of code
or might happened due to copying file from one OS to another OS

best you can install from Project guideline :-
https://github.com/mediabots/Linux-to-Windows-with-QEMU

Follow " How to Run the Script "

Regards
